package mx.cinvestav.edu.cinveslocatorclient.webservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.5
//
// Created by Quasar Development at 03-05-2015
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class TGVagent extends AttributeContainer implements KvmSerializable
{
    
    public String device;
    
    public Integer idagente;
    
    public String lastLogin;
    
    public String name;
    
    public TGVtype typeIdtype;

    public TGVagent ()
    {
    }

    public TGVagent (java.lang.Object paramObj,TGVExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("device"))
        {	
	        java.lang.Object obj = soapObject.getProperty("device");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.device = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.device = (String)obj;
            }    
        }
        if (soapObject.hasProperty("idagente"))
        {	
	        java.lang.Object obj = soapObject.getProperty("idagente");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.idagente = Integer.parseInt(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Integer){
                this.idagente = (Integer)obj;
            }    
        }
        if (soapObject.hasProperty("lastLogin"))
        {	
	        java.lang.Object obj = soapObject.getProperty("lastLogin");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.lastLogin = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.lastLogin = (String)obj;
            }    
        }
        if (soapObject.hasProperty("name"))
        {	
	        java.lang.Object obj = soapObject.getProperty("name");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.name = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.name = (String)obj;
            }    
        }
        if (soapObject.hasProperty("typeIdtype"))
        {	
	        java.lang.Object j = soapObject.getProperty("typeIdtype");
	        this.typeIdtype = (TGVtype)__envelope.get(j,TGVtype.class);
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.device!=null?this.device:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.idagente!=null?this.idagente:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.lastLogin!=null?this.lastLogin:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.name!=null?this.name:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.typeIdtype!=null?this.typeIdtype:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 5;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "device";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "idagente";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "lastLogin";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "name";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = TGVtype.class;
            info.name = "typeIdtype";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }
}
