package mx.cinvestav.edu.cinveslocatorclient.webservice;




//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.5
//
// Created by Quasar Development at 03-05-2015
//
//---------------------------------------------------




import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.*;
import org.ksoap2.transport.*;
import org.kxml2.kdom.Element;

import java.lang.reflect.Constructor;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class TGVCinvesLocatorPortBinding
{
    interface TGVIWcfMethod
    {
        TGVExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws java.lang.Exception;

        java.lang.Object ProcessResult(TGVExtendedSoapSerializationEnvelope __envelope,java.lang.Object result) throws java.lang.Exception;
    }

    String url="http://192.168.1.69:8080/CinvesLocatorServerWebService/CinvesLocator";

    int timeOut=60000;
    public List< HeaderProperty> httpHeaders;
    public boolean enableLogging;

    TGVIServiceEvents callback;
    public TGVCinvesLocatorPortBinding(){}

    public TGVCinvesLocatorPortBinding (TGVIServiceEvents callback)
    {
        this.callback = callback;
    }
    public TGVCinvesLocatorPortBinding(TGVIServiceEvents callback,String url)
    {
        this.callback = callback;
        this.url = url;
    }

    public TGVCinvesLocatorPortBinding(TGVIServiceEvents callback,String url,int timeOut)
    {
        this.callback = callback;
        this.url = url;
        this.timeOut=timeOut;
    }

    protected org.ksoap2.transport.Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                return new HttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            }
            else
            {
                return new HttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }
    
    protected TGVExtendedSoapSerializationEnvelope createEnvelope()
    {
        TGVExtendedSoapSerializationEnvelope envelope= new TGVExtendedSoapSerializationEnvelope(TGVExtendedSoapSerializationEnvelope.VER11);
        return envelope;
    }
    
    protected java.util.List sendRequest(String methodName,TGVExtendedSoapSerializationEnvelope envelope,org.ksoap2.transport.Transport transport  )throws java.lang.Exception
    {
        return transport.call(methodName, envelope, httpHeaders);
    }

    java.lang.Object getResult(java.lang.Class destObj,java.lang.Object source,String resultName,TGVExtendedSoapSerializationEnvelope __envelope) throws java.lang.Exception
    {
        if(source==null)
        {
            return null;
        }
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                java.lang.Object instance=__envelope.get(source,destObj);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                java.lang.Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                java.lang.Object instance=__envelope.get(j,destObj);
                return instance;
            }
            else if( soap.getName().equals(resultName)) {
                java.lang.Object instance=__envelope.get(source,destObj);
                return instance;
            }
       }

       return null;
    }

        
    public void saveAgent(final String name,final String device,final String last_login,final String type ) throws java.lang.Exception
    {
        execute(new TGVIWcfMethod()
        {
            @Override
            public TGVExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              TGVExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://webservice.locator.cinvestav.com/", "saveAgent");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="name";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(name!=null?name:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="device";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(device!=null?device:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="last_login";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(last_login!=null?last_login:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="type";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(type!=null?type:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(TGVExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return null;
            }
        },"");
    }
    
    public android.os.AsyncTask< Void, Void, TGVOperationResult< Void>> saveAgentAsync(final String name,final String device,final String last_login,final String type)
    {
        return executeAsync(new TGVFunctions.IFunc< Void>()
        {
            @Override
            public Void Func() throws java.lang.Exception {
                saveAgent( name,device,last_login,type);
                return null;
            }
        }) ;
    }
    
    public TGVgetTypeAgentResponse getTypeAgent(final String type ) throws java.lang.Exception
    {
        return (TGVgetTypeAgentResponse)execute(new TGVIWcfMethod()
        {
            @Override
            public TGVExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              TGVExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://webservice.locator.cinvestav.com/", "getTypeAgent");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="type";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(type!=null?type:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(TGVExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (TGVgetTypeAgentResponse)getResult(TGVgetTypeAgentResponse.class,__result,"getTypeAgentResponse",__envelope);
            }
        },"");
    }
    
    public android.os.AsyncTask< Void, Void, TGVOperationResult< TGVgetTypeAgentResponse>> getTypeAgentAsync(final String type)
    {
        return executeAsync(new TGVFunctions.IFunc< TGVgetTypeAgentResponse>() {
            public TGVgetTypeAgentResponse Func() throws java.lang.Exception {
                return getTypeAgent( type);
            }
        });
    }
    
    public TGVlocation getLastLocation(final String name ) throws java.lang.Exception
    {
        return (TGVlocation)execute(new TGVIWcfMethod()
        {
            @Override
            public TGVExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              TGVExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://webservice.locator.cinvestav.com/", "getLastLocation");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="name";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(name!=null?name:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(TGVExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (TGVlocation)getResult(TGVlocation.class,__result,"return",__envelope);
            }
        },"");
    }
    
    public android.os.AsyncTask< Void, Void, TGVOperationResult< TGVlocation>> getLastLocationAsync(final String name)
    {
        return executeAsync(new TGVFunctions.IFunc< TGVlocation>() {
            public TGVlocation Func() throws java.lang.Exception {
                return getLastLocation( name);
            }
        });
    }
    
    public void saveLocation(final String name,final String timestamp,final String coordinates ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    }
    
    public android.os.AsyncTask< Void, Void, TGVOperationResult< Void>> saveLocationAsync(final String name,final String timestamp,final String coordinates)
    {
        return executeAsync(new TGVFunctions.IFunc< Void>()
        {
            @Override
            public Void Func() throws java.lang.Exception {
                saveLocation( name,timestamp,coordinates);
                return null;
            }
        }) ;
    }
    
    public String getAgent(final String name ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, TGVOperationResult< String>> getAgentAsync(final String name)
    {
        return executeAsync(new TGVFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return getAgent( name);
            }
        });
    }

    
    protected java.lang.Object execute(TGVIWcfMethod wcfMethod,String methodName) throws java.lang.Exception
    {
        org.ksoap2.transport.Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        TGVExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport);
            
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump",__httpTransport.requestDump);
                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }
    
    protected < T> android.os.AsyncTask< Void, Void, TGVOperationResult< T>>  executeAsync(final TGVFunctions.IFunc< T> func)
    {
        return new android.os.AsyncTask< Void, Void, TGVOperationResult< T>>()
        {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            };
            @Override
            protected TGVOperationResult< T> doInBackground(Void... params) {
                TGVOperationResult< T> result = new TGVOperationResult< T>();
                try
                {
                    result.Result= func.Func();
                }
                catch(java.lang.Exception ex)
                {
                    ex.printStackTrace();
                    result.Exception=ex;
                }
                return result;
            }
            
            @Override
            protected void onPostExecute(TGVOperationResult< T> result)
            {
                callback.Completed(result);
            }
        }.execute();
    }
        
    java.lang.Exception convertToException(org.ksoap2.SoapFault fault,TGVExtendedSoapSerializationEnvelope envelope)
    {

        if(fault.detail!=null && fault.detail.getChildCount()>0)
        {
            Element detailsNode=(Element)fault.detail.getChild(0);
            try
            {
                SoapObject exceptionObject = null;
                exceptionObject=envelope.GetExceptionDetail(detailsNode,"http://webservice.locator.cinvestav.com/","LocatorException");
                if (exceptionObject != null)
                {
                    return new TGVLocatorException(exceptionObject,envelope);
                }
            }
            catch (java.lang.Exception e)
            {
                e.printStackTrace();
            }
        }
        return new java.lang.Exception(fault.faultstring);
    }
}


