package mx.cinvestav.edu.cinveslocatorclient.webservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.5
//
// Created by Quasar Development at 03-05-2015
//
//---------------------------------------------------



public interface TGVIServiceEvents
{
    public void Starting();
    public void Completed(TGVOperationResult result);
}
