package mx.cinvestav.edu.cinveslocatorclient.webservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.5
//
// Created by Quasar Development at 03-05-2015
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class TGVlocation extends AttributeContainer implements KvmSerializable
{
    
    public TGVagent agenteIdagente;
    
    public String coordinates;
    
    public Integer idlocation;
    
    public String timestamp;

    public TGVlocation ()
    {
    }

    public TGVlocation (java.lang.Object paramObj,TGVExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("agenteIdagente"))
        {	
	        java.lang.Object j = soapObject.getProperty("agenteIdagente");
	        this.agenteIdagente = (TGVagent)__envelope.get(j,TGVagent.class);
        }
        if (soapObject.hasProperty("coordinates"))
        {	
	        java.lang.Object obj = soapObject.getProperty("coordinates");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.coordinates = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.coordinates = (String)obj;
            }    
        }
        if (soapObject.hasProperty("idlocation"))
        {	
	        java.lang.Object obj = soapObject.getProperty("idlocation");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.idlocation = Integer.parseInt(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Integer){
                this.idlocation = (Integer)obj;
            }    
        }
        if (soapObject.hasProperty("timestamp"))
        {	
	        java.lang.Object obj = soapObject.getProperty("timestamp");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.timestamp = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.timestamp = (String)obj;
            }    
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.agenteIdagente!=null?this.agenteIdagente:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.coordinates!=null?this.coordinates:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.idlocation!=null?this.idlocation:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.timestamp!=null?this.timestamp:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = TGVagent.class;
            info.name = "agenteIdagente";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "coordinates";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "idlocation";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "timestamp";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }
}
